### ISSUE TITLE
trpc create 生成不了validate.go文件吗

### ISSUE THREAD

**Issue by themoredu** [trpc-group/trpc-cmdline#11]

**Comment by hitzhangjie** [comment]
如果您指的是protoc-gen-validate生成的validate.go的话，嗯，trpc create --secvenabled -p<pb>,

此时会调用插件protoc-gen-secv生成一个validate.go，protoc-gen-secv是受protoc-gen-validate启发，
并结合了一些安全方面的实践开发的一个代码生成工具。

ps：trpc命令行工具依赖一些插件，可以运行 `trpc setup`来完成相关检查、设置。

**Comment by WineChord** [comment]
内网用的没有开源出来，我看看提供一个开源版的

**Comment by WineChord** [comment]
现在已经支持了，可以重新 go install latest，然后看下文档 https://github.com/trpc-group/trpc-cmdline/blob/main/docs/examples/example-2/README.zh_CN.md#%E7%94%9F%E6%88%90-validatepbgo-%E6%96%87%E4%BB%B6
