### ISSUE TITLE
affected/package: trpc alias not work 

### ISSUE THREAD

**Issue by mmtbak** [trpc-group/trpc-cmdline#32]
### What version of trpc-cmdline are you using?
trpc-group/trpc-cmdline version: v1.0.5

### Does this issue reproduce with the latest release?
yes 

### What operating system and processor architecture are you using (`go env`)?
CentOS 7.9
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOVERSION="go1.20.10"

</pre></details>

### What did you do?
i want create *go file and swagger.json file  from proto file use by  trpc-cmdline . use alias tag 

helloword.proto

```
// HelloWorldService handles hello request and echo message.
service HelloWorldService {
  // Hello says hello.
  rpc Hello(HelloRequest) returns(HelloResponse);

  // Apply
  //@alias="/api/apply"
  rpc Apply(ApplyRequest) returns(ApplyResponse){};
}

```

use trpc command line 

`trpc create -p ./helloworld.proto -o helloworld --rpconly --swagger --alias`

> [create] run goimports -w . error: exit status 2,
> helloworld.trpc.go:89:40: missing ',' in composite literal
> helloworld.trpc.go:103:5: missing ',' in composite literal
> helloworld.trpc.go:104:71: missing ',' before newline in composite literal
> helloworld.trpc.go:105:6: missing ',' before newline in composite literal
> helloworld.trpc.go:106:2: missing ',' before newline in composite literal
> helloworld.trpc.go:112:1: expected operand, found 'type'
> helloworld.trpc.go:116:52: missing ',' in argument list
> helloworld.trpc.go:117:5: missing ',' in argument list
> helloworld.trpc.go:118:1: expected operand, found '}'
> helloworld.trpc.go:121:5: missing ',' in argument list
> helloworld.trpc.go:122:1: expected operand, found '}'
> 
> Execution err:
>         running plugin `goimports`, err: exit status 2
> Please run "trpc -h" or "trpc create -h" (or "trpc {some-other-subcommand} -h") for help messages.
> 

in  helloworld.trpc.go ,it show error 

```
            {
                Name: ""/api/apply"",
                Func: HelloWorldServiceService_Apply_Handler,
                
            },
```
double ' " '  made it error .  

if i cancel  `--alias` arg, it works good . 
but i want  use  'alias' tag define my own url , so  what should i do now？ 

### What did you expect to see?

alias tag work well . 
in that case , in  swagger file ,this api  
```
path = /api/apply
summary = Apply
```

### What did you see instead?

**Comment by WineChord** [comment]
Write just `//@alias=/api/apply` instead of `//@alias="/api/apply"`.

**Comment by WineChord** [comment]
The alias parsed should have the quotes `"` stripped to be more robust.

Adding some code to [this place](https://github.com/trpc-group/trpc-cmdline/blob/962306af96cd7dddd2fd336ec887a6cf3a65d2f5/parser/fill.go#L523) should work.

This is a good starting point to invite contributors.

**Comment by mmtbak** [comment]
> Write just `//@alias=/api/apply` instead of `//@alias="/api/apply"`.

it does not work . 

1.  it use `"` in the doc  ,  https://github.com/trpc-group/trpc-cmdline/blob/main/docs/examples/example-2/README.zh_CN.md
2.` //@alias=/api/apply` does not work , in swagger.json.
```
 "paths": {
  "/helloworld.HelloWorldService/Apply": {
   "post": {
    "summary": "Apply\n// // @alias=/api/apply",
    "operationId": "Apply",
```
`path` and `summary` is incorrect

**Comment by WineChord** [comment]
https://github.com/trpc-group/trpc-cmdline/pull/33 fixes double quotes.

**Comment by WineChord** [comment]
#34 fixes summary.

**Comment by WineChord** [comment]
@mmtbak Hi, try installing the latest version:

```shell
go install trpc.group/trpc-go/trpc-cmdline/trpc@latest
```

https://github.com/trpc-group/trpc-cmdline/releases/tag/v1.0.6

**Comment by mmtbak** [comment]
> @mmtbak Hi, try installing the latest version:
> 
> ```shell
> go install trpc.group/trpc-go/trpc-cmdline/trpc@latest
> ```
> 
> https://github.com/trpc-group/trpc-cmdline/releases/tag/v1.0.6

no ,this version doest not work at all 

```
trpc version 
trpc-group/trpc-cmdline version: v1.0.6
```
hello.proto
```
// HelloWorldService handles hello request and echo message.
service HelloWorldService {
  // Hello says hello.
  rpc Hello(HelloRequest) returns(HelloResponse);
  // Apply Resource
  //@alias=/api/hello
  rpc Apply(ApplyRequest) returns(ApplyResponse){};

}
```
`trpc create -p ./proto/helloworld.proto -o helloworld --rpconly --swagger`

apidocs.swagger.json

```
"paths": {
  "/helloworld.HelloWorldService/Apply": {
   "post": {
    "summary": "Apply Resource",
    "operationId": "Apply",
    "responses": {
     "200": {
      "description": "ApplyResponse",
      "schema": {
       "$ref": "#/definitions/helloworld.ApplyResponse"
      }
     }
    },
```
there is nothing like  `api/hello` in swagger file or  trpc_pb.go or pb.go file

**Comment by WineChord** [comment]
@mmtbak 
![image](https://github.com/trpc-group/trpc-cmdline/assets/20353612/50359eba-d2b9-4d5d-baaa-6ac61e21c8bf)
https://github.com/trpc-group/trpc-cmdline/blob/main/docs/examples/example-2/README.zh_CN.md
