### ISSUE TITLE
trpc setup failed

### ISSUE THREAD

**Issue by tyanxie** [trpc-group/trpc-cmdline#40]
### What version of trpc-cmdline are you using?

v1.0.8

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/tyanxie/Library/Caches/go-build'
GOENV='/Users/tyanxie/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/tyanxie/Projects/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/tyanxie/Projects/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/Users/tyanxie/DevTools/gos/go1.22.2'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/tyanxie/DevTools/gos/go1.22.2/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/z8/0hqvm5bx7058y4tghsqv9q2h0000gn/T/go-build2085974099=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

run `trpc setup`

### What did you expect to see?

install mockgen command-line success

### What did you see instead?

install mockgen command-line failed

<img width="1536" alt="Snipaste_2024-05-17_07-55-30" src="https://github.com/trpc-group/trpc-cmdline/assets/48086225/382005ee-fd03-486c-953f-ca7aaaf5a237">

### My guess

maybe the installation path is set to `~/go/bin`, but I expected `$(go env GOPATH)/bin`, like what `go install` does by default

**Comment by WineChord** [comment]
@tyanxie Try https://github.com/trpc-group/trpc-cmdline/releases/tag/v1.0.9
